include: package:flutter_lints/flutter.yaml

linter:    

  rules:
    // ignore: non_constant_identifier_name

analyzer:
  exclude:
    - bricks/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore